name: openbalena-cloudflare

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARE_TUNNEL_TOKEN}"]
    depends_on:
      - api
      - registry
    networks:
      - openbalena_net

networks:
  openbalena_net:
    external: false
