services:
  inference-node-yolo-seed-node-admin-browser-primary:
    build:
      context: "../apps/inference-node-yolo"
      dockerfile: "Dockerfile"
    environment:
      INFERENCE_BRIDGE_URL: "http://inference-bridge:8090"
      NODE_ID: "seed-node-admin-browser-primary"
      NODE_RUNTIME: "yolo"
      NODE_TRANSPORT: "http"
      NODE_ENDPOINT: "http://seed-node-admin-browser-primary:8091"
      NODE_TENANT_ID: "cmnm61o4r0007w1x67sehdahw"
      NODE_TENANT_IDS: "cmnm61o4r0007w1x67sehdahw"
      NODE_TASK_TYPES: "person_detection"
      NODE_MODELS: "seed-yolo26-person-balanced"
      NODE_MAX_CONCURRENT: "3"
      NODE_RESOURCES_CPU: "4"
      NODE_RESOURCES_GPU: "0"
      NODE_RESOURCES_VRAM_MB: "0"
      NODE_HEARTBEAT_INTERVAL_MS: "10000"
      NODE_CONTRACT_VERSION: "1.0"
      NODE_AUTH_ADMIN_SECRET: "${NODE_AUTH_ADMIN_SECRET}"
    ports:
      - "8091:8091"
    depends_on:
      - "inference-bridge"
    networks:
      - "nearhome_net"
  inference-node-yolo-seed-node-nhdp21-validation:
    build:
      context: "../apps/inference-node-yolo"
      dockerfile: "Dockerfile"
    environment:
      INFERENCE_BRIDGE_URL: "http://inference-bridge:8090"
      NODE_ID: "seed-node-nhdp21-validation"
      NODE_RUNTIME: "yolo"
      NODE_TRANSPORT: "http"
      NODE_ENDPOINT: "http://seed-node-nhdp21-validation:8091"
      NODE_TENANT_ID: "cmnm61o4p0004w1x62e2yea5n"
      NODE_TENANT_IDS: "cmnm61o4p0004w1x62e2yea5n"
      NODE_TASK_TYPES: "face_detection"
      NODE_MODELS: "seed-yolo26-face-balanced"
      NODE_MAX_CONCURRENT: "2"
      NODE_RESOURCES_CPU: "4"
      NODE_RESOURCES_GPU: "0"
      NODE_RESOURCES_VRAM_MB: "0"
      NODE_HEARTBEAT_INTERVAL_MS: "10000"
      NODE_CONTRACT_VERSION: "1.0"
      NODE_AUTH_ADMIN_SECRET: "${NODE_AUTH_ADMIN_SECRET}"
    ports:
      - "8091:8091"
    depends_on:
      - "inference-bridge"
    networks:
      - "nearhome_net"
